ARG RENPY_VERSION=8.2.1

FROM busybox as renios
ARG RENPY_VERSION
RUN wget -O renios.zip https://www.renpy.org/dl/$RENPY_VERSION/renpy-$RENPY_VERSION-renios.zip && \
    unzip renios.zip && \
    rm renios.zip && \
    mv renios/* /renios

FROM dinaki/renpy:$RENPY_VERSION
COPY --from=renios /renios /opt/renpy/renios

RUN sh /opt/renpy/renpy.sh launcher set_project /game
WORKDIR /opt/renpy
